services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_app
    ports:
      - "5678:5678"
    environment:
      - TZ=America/Sao_Paulo
      - N8N_SECURE_COOKIE=false
      - N8N_WEBHOOK_CORS_ALLOWED_ORIGINS=http://localhost:3000,https://SEU-URL.vercel.app
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - python-api
      - postgres
      - redis

  python-api:
    container_name: music_api
    build: ./n8n-custom/python_api
    ports:
      - "8000:8000"
    volumes:
      - ./n8n-custom/python_api:/app

  postgres:
    image: postgres:15
    container_name: n8n_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pandora_secret_123
      - POSTGRES_DB=pandora_brain
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    container_name: n8n_redis
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  n8n_data:
    external: true
    name: n8n-custom_n8n_data
  postgres_data: {}
